name: gtm_control_tower
version: 1.0.0
config-version: 2
profile: gtm_control_tower
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]
models:
  gtm_control_tower:
    staging:
      +materialized: view
    marts:
      +materialized: table
